/**
 * Shopee SDK 1.6.1 API surface generated from shopee-sdk-1.6.1/src/managers.
 * Keep this file data-only; request behavior lives in index.ts.
 */

export type ShopeeSdkHttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH";

export interface ShopeeSdkApiDefinition {
  group: string;
  method: string;
  path: string;
  httpMethod: ShopeeSdkHttpMethod;
  auth: boolean;
  commaParams?: readonly string[];
}

export type ShopeeSdkApiMethod = (...args: any[]) => Promise<any>;
export type ShopeeSdkApiGroup = Record<string, ShopeeSdkApiMethod>;

export interface ShopeeSdkApiGroups {
  accountHealth: ShopeeSdkApiGroup;
  addOnDeal: ShopeeSdkApiGroup;
  ads: ShopeeSdkApiGroup;
  ams: ShopeeSdkApiGroup;
  auth: ShopeeSdkApiGroup;
  bundleDeal: ShopeeSdkApiGroup;
  discount: ShopeeSdkApiGroup;
  fbs: ShopeeSdkApiGroup;
  firstMile: ShopeeSdkApiGroup;
  followPrize: ShopeeSdkApiGroup;
  globalProduct: ShopeeSdkApiGroup;
  livestream: ShopeeSdkApiGroup;
  logistics: ShopeeSdkApiGroup;
  media: ShopeeSdkApiGroup;
  mediaSpace: ShopeeSdkApiGroup;
  merchant: ShopeeSdkApiGroup;
  order: ShopeeSdkApiGroup;
  payment: ShopeeSdkApiGroup;
  product: ShopeeSdkApiGroup;
  public: ShopeeSdkApiGroup;
  push: ShopeeSdkApiGroup;
  returns: ShopeeSdkApiGroup;
  sbs: ShopeeSdkApiGroup;
  shop: ShopeeSdkApiGroup;
  shopCategory: ShopeeSdkApiGroup;
  shopFlashSale: ShopeeSdkApiGroup;
  topPicks: ShopeeSdkApiGroup;
  video: ShopeeSdkApiGroup;
  voucher: ShopeeSdkApiGroup;
}

export type ShopeeSdkApiRequester = (
  definition: ShopeeSdkApiDefinition,
  params?: any,
) => Promise<any>;

export const SHOPEE_SDK_API_DEFINITIONS = [
  {
    group: "accountHealth",
    method: "getShopPenalty",
    path: "/account_health/shop_penalty",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getShopPerformance",
    path: "/account_health/get_shop_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getMetricSourceDetail",
    path: "/account_health/get_metric_source_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getPenaltyPointHistory",
    path: "/account_health/get_penalty_point_history",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getPunishmentHistory",
    path: "/account_health/get_punishment_history",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getListingsWithIssues",
    path: "/account_health/get_listings_with_issues",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "accountHealth",
    method: "getLateOrders",
    path: "/account_health/get_late_orders",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "addAddOnDeal",
    path: "/add_on_deal/add_add_on_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "addAddOnDealMainItem",
    path: "/add_on_deal/add_add_on_deal_main_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "addAddOnDealSubItem",
    path: "/add_on_deal/add_add_on_deal_sub_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "deleteAddOnDeal",
    path: "/add_on_deal/delete_add_on_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "deleteAddOnDealMainItem",
    path: "/add_on_deal/delete_add_on_deal_main_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "deleteAddOnDealSubItem",
    path: "/add_on_deal/delete_add_on_deal_sub_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "endAddOnDeal",
    path: "/add_on_deal/end_add_on_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "getAddOnDeal",
    path: "/add_on_deal/get_add_on_deal",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "getAddOnDealList",
    path: "/add_on_deal/get_add_on_deal_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "getAddOnDealMainItem",
    path: "/add_on_deal/get_add_on_deal_main_item",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "getAddOnDealSubItem",
    path: "/add_on_deal/get_add_on_deal_sub_item",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "updateAddOnDeal",
    path: "/add_on_deal/update_add_on_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "updateAddOnDealMainItem",
    path: "/add_on_deal/update_add_on_deal_main_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "addOnDeal",
    method: "updateAddOnDealSubItem",
    path: "/add_on_deal/update_add_on_deal_sub_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "getTotalBalance",
    path: "/ads/get_total_balance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getShopToggleInfo",
    path: "/ads/get_shop_toggle_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getRecommendedKeywordList",
    path: "/ads/get_recommended_keyword_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getRecommendedItemList",
    path: "/ads/get_recommended_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getAllCpcAdsHourlyPerformance",
    path: "/ads/get_all_cpc_ads_hourly_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getAllCpcAdsDailyPerformance",
    path: "/ads/get_all_cpc_ads_daily_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getProductCampaignDailyPerformance",
    path: "/ads/get_product_campaign_daily_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getProductCampaignHourlyPerformance",
    path: "/ads/get_product_campaign_hourly_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getProductLevelCampaignIdList",
    path: "/ads/get_product_level_campaign_id_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getProductLevelCampaignSettingInfo",
    path: "/ads/get_product_level_campaign_setting_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getProductRecommendedRoiTarget",
    path: "/ads/get_product_recommended_roi_target",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "checkCreateGmsProductCampaignEligibility",
    path: "/ads/check_create_gms_product_campaign_eligibility",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "createAutoProductAds",
    path: "/ads/create_auto_product_ads",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "createGmsProductCampaign",
    path: "/ads/create_gms_product_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "createManualProductAds",
    path: "/ads/create_manual_product_ads",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "editAutoProductAds",
    path: "/ads/edit_auto_product_ads",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "editGmsItemProductCampaign",
    path: "/ads/edit_gms_item_product_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "editGmsProductCampaign",
    path: "/ads/edit_gms_product_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "editManualProductAdKeywords",
    path: "/ads/edit_manual_product_ad_keywords",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "editManualProductAds",
    path: "/ads/edit_manual_product_ads",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "getAdsFacilShopRate",
    path: "/ads/get_ads_facil_shop_rate",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getCreateProductAdBudgetSuggestion",
    path: "/ads/get_create_product_ad_budget_suggestion",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ads",
    method: "getGmsCampaignPerformance",
    path: "/ads/get_gms_campaign_performance",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "getGmsItemPerformance",
    path: "/ads/get_gms_item_performance",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ads",
    method: "listGmsUserDeletedItem",
    path: "/ads/list_gms_user_deleted_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "addAllProductsToOpenCampaign",
    path: "/ams/add_all_products_to_open_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "batchAddProductsToOpenCampaign",
    path: "/ams/batch_add_products_to_open_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "batchEditProductsOpenCampaignSetting",
    path: "/ams/batch_edit_products_open_campaign_setting",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "batchGetProductsSuggestedRate",
    path: "/ams/batch_get_products_suggested_rate",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "batchRemoveProductsOpenCampaignSetting",
    path: "/ams/batch_remove_products_open_campaign_setting",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "editAllProductsOpenCampaignSetting",
    path: "/ams/edit_all_products_open_campaign_setting",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "getOpenCampaignAddedProduct",
    path: "/ams/get_open_campaign_added_product",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getOpenCampaignBatchTaskResult",
    path: "/ams/get_open_campaign_batch_task_result",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getOpenCampaignNotAddedProduct",
    path: "/ams/get_open_campaign_not_added_product",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getOpenCampaignPerformance",
    path: "/ams/get_open_campaign_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "removeAllProductsOpenCampaignSetting",
    path: "/ams/remove_all_products_open_campaign_setting",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "createNewTargetedCampaign",
    path: "/ams/create_new_targeted_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "editAffiliateListOfTargetedCampaign",
    path: "/ams/edit_affiliate_list_of_targeted_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "editProductListOfTargetedCampaign",
    path: "/ams/edit_product_list_of_targeted_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "getTargetedCampaignAddableProductList",
    path: "/ams/get_targeted_campaign_addable_product_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getTargetedCampaignList",
    path: "/ams/get_targeted_campaign_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getTargetedCampaignPerformance",
    path: "/ams/get_targeted_campaign_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getTargetedCampaignSettings",
    path: "/ams/get_targeted_campaign_settings",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "terminateTargetedCampaign",
    path: "/ams/terminate_targeted_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "updateBasicInfoOfTargetedCampaign",
    path: "/ams/update_basic_info_of_targeted_campaign",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "ams",
    method: "getAffiliatePerformance",
    path: "/ams/get_affiliate_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getAutoAddNewProductToggleStatus",
    path: "/ams/get_auto_add_new_product_toggle_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getCampaignKeyMetricsPerformance",
    path: "/ams/get_campaign_key_metrics_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getContentPerformance",
    path: "/ams/get_content_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getConversionReport",
    path: "/ams/get_conversion_report",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getManagedAffiliateList",
    path: "/ams/get_managed_affiliate_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getOptimizationSuggestionProduct",
    path: "/ams/get_optimization_suggestion_product",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getPerformanceDataUpdateTime",
    path: "/ams/get_performance_data_update_time",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getProductPerformance",
    path: "/ams/get_product_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getRecommendedAffiliateList",
    path: "/ams/get_recommended_affiliate_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getShopPerformance",
    path: "/ams/get_shop_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getShopSuggestedRate",
    path: "/ams/get_shop_suggested_rate",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getValidationList",
    path: "/ams/get_validation_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "getValidationReport",
    path: "/ams/get_validation_report",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "queryAffiliateList",
    path: "/ams/query_affiliate_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "ams",
    method: "updateAutoAddNewProductSetting",
    path: "/ams/update_auto_add_new_product_setting",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "auth",
    method: "getAccessToken",
    path: "/auth/token/get",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "auth",
    method: "getAccessTokenByResendCode",
    path: "/public/get_token_by_resend_code",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "auth",
    method: "getRefreshToken",
    path: "/auth/access_token/get",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "bundleDeal",
    method: "addBundleDeal",
    path: "/bundle_deal/add_bundle_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "addBundleDealItem",
    path: "/bundle_deal/add_bundle_deal_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "deleteBundleDeal",
    path: "/bundle_deal/delete_bundle_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "deleteBundleDealItem",
    path: "/bundle_deal/delete_bundle_deal_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "endBundleDeal",
    path: "/bundle_deal/end_bundle_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "getBundleDeal",
    path: "/bundle_deal/get_bundle_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "getBundleDealItem",
    path: "/bundle_deal/get_bundle_deal_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "getBundleDealList",
    path: "/bundle_deal/get_bundle_deal_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "updateBundleDeal",
    path: "/bundle_deal/update_bundle_deal",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "bundleDeal",
    method: "updateBundleDealItem",
    path: "/bundle_deal/update_bundle_deal_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "addDiscount",
    path: "/discount/add_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "addDiscountItem",
    path: "/discount/add_discount_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "deleteDiscount",
    path: "/discount/delete_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "deleteDiscountItem",
    path: "/discount/delete_discount_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "endDiscount",
    path: "/discount/end_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "getDiscount",
    path: "/discount/get_discount",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "discount",
    method: "getDiscountList",
    path: "/discount/get_discount_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "discount",
    method: "updateDiscount",
    path: "/discount/update_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "updateDiscountItem",
    path: "/discount/update_discount_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "getSipDiscounts",
    path: "/discount/get_sip_discounts",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "discount",
    method: "setSipDiscount",
    path: "/discount/set_sip_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "discount",
    method: "deleteSipDiscount",
    path: "/discount/delete_sip_discount",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "fbs",
    method: "queryBrShopEnrollmentStatus",
    path: "/fbs/query_br_shop_enrollment_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "fbs",
    method: "queryBrShopBlockStatus",
    path: "/fbs/query_br_shop_block_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "fbs",
    method: "queryBrShopInvoiceError",
    path: "/fbs/query_br_shop_invoice_error",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "fbs",
    method: "queryBrSkuBlockStatus",
    path: "/fbs/query_br_sku_block_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "bindCourierDeliveryFirstMileTrackingNumber",
    path: "/first_mile/bind_courier_delivery_first_mile_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "bindFirstMileTrackingNumber",
    path: "/first_mile/bind_first_mile_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "generateAndBindFirstMileTrackingNumber",
    path: "/first_mile/generate_and_bind_first_mile_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "generateFirstMileTrackingNumber",
    path: "/first_mile/generate_first_mile_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getChannelList",
    path: "/first_mile/get_channel_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getCourierDeliveryChannelList",
    path: "/first_mile/get_courier_delivery_channel_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getCourierDeliveryDetail",
    path: "/first_mile/get_courier_delivery_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getCourierDeliveryTrackingNumberList",
    path: "/first_mile/get_courier_delivery_tracking_number_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getCourierDeliveryWaybill",
    path: "/first_mile/get_courier_delivery_waybill",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getDetail",
    path: "/first_mile/get_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getTrackingNumberList",
    path: "/first_mile/get_tracking_number_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getTransitWarehouseList",
    path: "/first_mile/get_transit_warehouse_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getUnbindOrderList",
    path: "/first_mile/get_unbind_order_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "firstMile",
    method: "getWaybill",
    path: "/first_mile/get_waybill",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "unbindFirstMileTrackingNumber",
    path: "/first_mile/unbind_first_mile_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "firstMile",
    method: "unbindFirstMileTrackingNumberAll",
    path: "/first_mile/unbind_first_mile_tracking_number_all",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "followPrize",
    method: "addFollowPrize",
    path: "/follow_prize/add_follow_prize",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "followPrize",
    method: "deleteFollowPrize",
    path: "/follow_prize/delete_follow_prize",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "followPrize",
    method: "endFollowPrize",
    path: "/follow_prize/end_follow_prize",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "followPrize",
    method: "getFollowPrizeDetail",
    path: "/follow_prize/get_follow_prize_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "followPrize",
    method: "getFollowPrizeList",
    path: "/follow_prize/get_follow_prize_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "followPrize",
    method: "updateFollowPrize",
    path: "/follow_prize/update_follow_prize",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getCategory",
    path: "/global_product/get_category",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getGlobalItemList",
    path: "/global_product/get_global_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getGlobalItemInfo",
    path: "/global_product/get_global_item_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getGlobalModelList",
    path: "/global_product/get_global_model_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "addGlobalItem",
    path: "/global_product/add_global_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateGlobalItem",
    path: "/global_product/update_global_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "deleteGlobalItem",
    path: "/global_product/delete_global_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "addGlobalModel",
    path: "/global_product/add_global_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateGlobalModel",
    path: "/global_product/update_global_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "deleteGlobalModel",
    path: "/global_product/delete_global_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "initTierVariation",
    path: "/global_product/init_tier_variation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateTierVariation",
    path: "/global_product/update_tier_variation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateStock",
    path: "/global_product/update_stock",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updatePrice",
    path: "/global_product/update_price",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getAttributeTree",
    path: "/global_product/get_attribute_tree",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getBrandList",
    path: "/global_product/get_brand_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "categoryRecommend",
    path: "/global_product/category_recommend",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getGlobalItemLimit",
    path: "/global_product/get_global_item_limit",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getPublishableShop",
    path: "/global_product/get_publishable_shop",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getShopPublishableStatus",
    path: "/global_product/get_shop_publishable_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "createPublishTask",
    path: "/global_product/create_publish_task",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getPublishTaskResult",
    path: "/global_product/get_publish_task_result",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getPublishedList",
    path: "/global_product/get_published_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getGlobalItemId",
    path: "/global_product/get_global_item_id",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getRecommendAttribute",
    path: "/global_product/get_recommend_attribute",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "searchGlobalAttributeValueList",
    path: "/global_product/search_global_attribute_value_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getVariations",
    path: "/global_product/get_variations",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "setSyncField",
    path: "/global_product/set_sync_field",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getLocalAdjustmentRate",
    path: "/global_product/get_local_adjustment_rate",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateLocalAdjustmentRate",
    path: "/global_product/update_local_adjustment_rate",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getSizeChartList",
    path: "/global_product/get_size_chart_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "getSizeChartDetail",
    path: "/global_product/get_size_chart_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "updateSizeChart",
    path: "/global_product/update_size_chart",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "globalProduct",
    method: "supportSizeChart",
    path: "/global_product/support_size_chart",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "livestream",
    method: "createSession",
    path: "/livestream/create_session",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "startSession",
    path: "/livestream/start_session",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "endSession",
    path: "/livestream/end_session",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "updateSession",
    path: "/livestream/update_session",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "getSessionDetail",
    path: "/livestream/get_session_detail",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getSessionMetric",
    path: "/livestream/get_session_metric",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getSessionItemMetric",
    path: "/livestream/get_session_item_metric",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "addItemList",
    path: "/livestream/add_item_list",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "updateItemList",
    path: "/livestream/update_item_list",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "deleteItemList",
    path: "/livestream/delete_item_list",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "getItemList",
    path: "/livestream/get_item_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getItemCount",
    path: "/livestream/get_item_count",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getRecentItemList",
    path: "/livestream/get_recent_item_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getLikeItemList",
    path: "/livestream/get_like_item_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "applyItemSet",
    path: "/livestream/apply_item_set",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "getItemSetList",
    path: "/livestream/get_item_set_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getItemSetItemList",
    path: "/livestream/get_item_set_item_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "getShowItem",
    path: "/livestream/get_show_item",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "updateShowItem",
    path: "/livestream/update_show_item",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "deleteShowItem",
    path: "/livestream/delete_show_item",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "postComment",
    path: "/livestream/post_comment",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "getLatestCommentList",
    path: "/livestream/get_latest_comment_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "livestream",
    method: "banUserComment",
    path: "/livestream/ban_user_comment",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "unbanUserComment",
    path: "/livestream/unban_user_comment",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "livestream",
    method: "uploadImage",
    path: "/livestream/upload_image",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "logistics",
    method: "getChannelList",
    path: "/logistics/get_channel_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getPauseStatus",
    path: "/logistics/get_pause_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "setPauseStatus",
    path: "/logistics/set_pause_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getShippingParameter",
    path: "/logistics/get_shipping_parameter",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getTrackingNumber",
    path: "/logistics/get_tracking_number",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "shipOrder",
    path: "/logistics/ship_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getAddressList",
    path: "/logistics/get_address_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getTrackingInfo",
    path: "/logistics/get_tracking_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "batchShipOrder",
    path: "/logistics/batch_ship_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "massShipOrder",
    path: "/logistics/mass_ship_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "shipBooking",
    path: "/logistics/ship_booking",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingShippingParameter",
    path: "/logistics/get_booking_shipping_parameter",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingTrackingInfo",
    path: "/logistics/get_booking_tracking_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingTrackingNumber",
    path: "/logistics/get_booking_tracking_number",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "getMassShippingParameter",
    path: "/logistics/get_mass_shipping_parameter",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getMassTrackingNumber",
    path: "/logistics/get_mass_tracking_number",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "setAddressConfig",
    path: "/logistics/set_address_config",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "deleteAddress",
    path: "/logistics/delete_address",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "createShippingDocument",
    path: "/logistics/create_shipping_document",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "downloadShippingDocument",
    path: "/logistics/download_shipping_document",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getShippingDocumentParameter",
    path: "/logistics/get_shipping_document_parameter",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getShippingDocumentResult",
    path: "/logistics/get_shipping_document_result",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getShippingDocumentDataInfo",
    path: "/logistics/get_shipping_document_data_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "createBookingShippingDocument",
    path: "/logistics/create_booking_shipping_document",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "downloadBookingShippingDocument",
    path: "/logistics/download_booking_shipping_document",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingShippingDocumentParameter",
    path: "/logistics/get_booking_shipping_document_parameter",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingShippingDocumentResult",
    path: "/logistics/get_booking_shipping_document_result",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getBookingShippingDocumentDataInfo",
    path: "/logistics/get_booking_shipping_document_data_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "createShippingDocumentJob",
    path: "/logistics/create_shipping_document_job",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "downloadShippingDocumentJob",
    path: "/logistics/download_shipping_document_job",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getShippingDocumentJobStatus",
    path: "/logistics/get_shipping_document_job_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "downloadToLabel",
    path: "/logistics/download_to_label",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateChannel",
    path: "/logistics/update_channel",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateShippingOrder",
    path: "/logistics/update_shipping_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateTrackingStatus",
    path: "/logistics/update_tracking_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateSelfCollectionOrderLogistics",
    path: "/logistics/update_self_collection_order_logistics",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getOperatingHours",
    path: "/logistics/get_operating_hours",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateOperatingHours",
    path: "/logistics/update_operating_hours",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getOperatingHourRestrictions",
    path: "/logistics/get_operating_hour_restrictions",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "deleteSpecialOperatingHour",
    path: "/logistics/delete_special_operating_hour",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "getMartPackagingInfo",
    path: "/logistics/get_mart_packaging_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "logistics",
    method: "setMartPackagingInfo",
    path: "/logistics/set_mart_packaging_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "batchUpdateTPFWarehouseTrackingStatus",
    path: "/logistics/batch_update_tpf_warehouse_tracking_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "checkPolygonUpdateStatus",
    path: "/logistics/check_polygon_update_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "updateAddress",
    path: "/logistics/update_address",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "logistics",
    method: "uploadServiceablePolygon",
    path: "/logistics/upload_serviceable_polygon",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "mediaSpace",
    method: "uploadImage",
    path: "/media_space/upload_image",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "mediaSpace",
    method: "initVideoUpload",
    path: "/media_space/init_video_upload",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "mediaSpace",
    method: "uploadVideoPart",
    path: "/media_space/upload_video_part",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "mediaSpace",
    method: "completeVideoUpload",
    path: "/media_space/complete_video_upload",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "mediaSpace",
    method: "getVideoUploadResult",
    path: "/media_space/get_video_upload_result",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "mediaSpace",
    method: "cancelVideoUpload",
    path: "/media_space/cancel_video_upload",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "media",
    method: "uploadMediaImage",
    path: "/media/upload_image",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "media",
    method: "uploadImage",
    path: "/media_space/upload_image",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "media",
    method: "initVideoUpload",
    path: "/media_space/init_video_upload",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "media",
    method: "uploadVideoPart",
    path: "/media_space/upload_video_part",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "media",
    method: "completeVideoUpload",
    path: "/media_space/complete_video_upload",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "media",
    method: "getVideoUploadResult",
    path: "/media_space/get_video_upload_result",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "media",
    method: "cancelVideoUpload",
    path: "/media_space/cancel_video_upload",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "merchant",
    method: "getMerchantInfo",
    path: "/merchant/get_merchant_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "merchant",
    method: "getMerchantPrepaidAccountList",
    path: "/merchant/get_merchant_prepaid_account_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "merchant",
    method: "getMerchantWarehouseList",
    path: "/merchant/get_merchant_warehouse_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "merchant",
    method: "getMerchantWarehouseLocationList",
    path: "/merchant/get_merchant_warehouse_location_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "merchant",
    method: "getShopListByMerchant",
    path: "/merchant/get_shop_list_by_merchant",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "merchant",
    method: "getWarehouseEligibleShopList",
    path: "/merchant/get_warehouse_eligible_shop_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getOrderList",
    path: "/order/get_order_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "getOrdersDetail",
    path: "/order/get_order_detail",
    httpMethod: "GET",
    auth: true,
    commaParams: ["order_sn_list"],
  },
  {
    group: "order",
    method: "getShipmentList",
    path: "/order/get_shipment_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "splitOrder",
    path: "/order/split_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "unsplitOrder",
    path: "/order/unsplit_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "cancelOrder",
    path: "/order/cancel_order",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getBuyerInvoiceInfo",
    path: "/order/get_buyer_invoice_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "setNote",
    path: "/order/set_note",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getPackageDetail",
    path: "/order/get_package_detail",
    httpMethod: "GET",
    auth: true,
    commaParams: ["package_number_list"],
  },
  {
    group: "order",
    method: "handleBuyerCancellation",
    path: "/order/handle_buyer_cancellation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "searchPackageList",
    path: "/order/search_package_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getPendingBuyerInvoiceOrderList",
    path: "/order/get_pending_buyer_invoice_order_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "handlePrescriptionCheck",
    path: "/order/handle_prescription_check",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "downloadInvoiceDoc",
    path: "/order/download_invoice_doc",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "uploadInvoiceDoc",
    path: "/order/upload_invoice_doc",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getBookingDetail",
    path: "/order/get_booking_detail",
    httpMethod: "GET",
    auth: true,
    commaParams: ["booking_sn_list"],
  },
  {
    group: "order",
    method: "getBookingList",
    path: "/order/get_booking_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "getWarehouseFilterConfig",
    path: "/order/get_warehouse_filter_config",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "order",
    method: "downloadFbsInvoices",
    path: "/order/download_fbs_invoices",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "generateFbsInvoices",
    path: "/order/generate_fbs_invoices",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "order",
    method: "getFbsInvoicesResult",
    path: "/order/get_fbs_invoices_result",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "getEscrowDetail",
    path: "/payment/get_escrow_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getEscrowList",
    path: "/payment/get_escrow_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getEscrowDetailBatch",
    path: "/payment/get_escrow_detail_batch",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "getWalletTransactionList",
    path: "/payment/get_wallet_transaction_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getPaymentMethodList",
    path: "/payment/get_payment_method_list",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "payment",
    method: "getShopInstallmentStatus",
    path: "/payment/get_shop_installment_status",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "setShopInstallmentStatus",
    path: "/payment/set_shop_installment_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "getItemInstallmentStatus",
    path: "/payment/get_item_installment_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "setItemInstallmentStatus",
    path: "/payment/set_item_installment_status",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "generateIncomeReport",
    path: "/payment/generate_income_report",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getIncomeReport",
    path: "/payment/get_income_report",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "generateIncomeStatement",
    path: "/payment/generate_income_statement",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getIncomeStatement",
    path: "/payment/get_income_statement",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getBillingTransactionInfo",
    path: "/payment/get_billing_transaction_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "payment",
    method: "getPayoutDetail",
    path: "/payment/get_payout_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "payment",
    method: "getPayoutInfo",
    path: "/payment/get_payout_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getComment",
    path: "/product/get_comment",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "replyComment",
    path: "/product/reply_comment",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getItemList",
    path: "/product/get_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemBaseInfo",
    path: "/product/get_item_base_info",
    httpMethod: "GET",
    auth: true,
    commaParams: ["item_id_list"],
  },
  {
    group: "product",
    method: "getModelList",
    path: "/product/get_model_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "updatePrice",
    path: "/product/update_price",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateStock",
    path: "/product/update_stock",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "deleteItem",
    path: "/product/delete_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "unlistItem",
    path: "/product/unlist_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getCategory",
    path: "/product/get_category",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "addItem",
    path: "/product/add_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateItem",
    path: "/product/update_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "addModel",
    path: "/product/add_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateModel",
    path: "/product/update_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "deleteModel",
    path: "/product/delete_model",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "initTierVariation",
    path: "/product/init_tier_variation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateTierVariation",
    path: "/product/update_tier_variation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "searchItem",
    path: "/product/search_item",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemExtraInfo",
    path: "/product/get_item_extra_info",
    httpMethod: "GET",
    auth: true,
    commaParams: ["item_id_list"],
  },
  {
    group: "product",
    method: "getAttributeTree",
    path: "/product/get_attribute_tree",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getBrandList",
    path: "/product/get_brand_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "registerBrand",
    path: "/product/register_brand",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "categoryRecommend",
    path: "/product/category_recommend",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemLimit",
    path: "/product/get_item_limit",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemPromotion",
    path: "/product/get_item_promotion",
    httpMethod: "GET",
    auth: true,
    commaParams: ["item_id_list"],
  },
  {
    group: "product",
    method: "boostItem",
    path: "/product/boost_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getBoostedList",
    path: "/product/get_boosted_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getVariations",
    path: "/product/get_variations",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getRecommendAttribute",
    path: "/product/get_recommend_attribute",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "searchAttributeValueList",
    path: "/product/search_attribute_value_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getMainItemList",
    path: "/product/get_main_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemViolationInfo",
    path: "/product/get_item_violation_info",
    httpMethod: "GET",
    auth: true,
    commaParams: ["item_id_list"],
  },
  {
    group: "product",
    method: "getWeightRecommendation",
    path: "/product/get_weight_recommendation",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getDirectItemList",
    path: "/product/get_direct_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getItemContentDiagnosisResult",
    path: "/product/get_item_content_diagnosis_result",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getItemListByContentDiagnosis",
    path: "/product/get_item_list_by_content_diagnosis",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "addKitItem",
    path: "/product/add_kit_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateKitItem",
    path: "/product/update_kit_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getKitItemInfo",
    path: "/product/get_kit_item_info",
    httpMethod: "GET",
    auth: true,
    commaParams: ["item_id_list"],
  },
  {
    group: "product",
    method: "getKitItemLimit",
    path: "/product/get_kit_item_limit",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "generateKitImage",
    path: "/product/generate_kit_image",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "addSspItem",
    path: "/product/add_ssp_item",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getSspInfo",
    path: "/product/get_ssp_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getSspList",
    path: "/product/get_ssp_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "linkSsp",
    path: "/product/link_ssp",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "unlinkSsp",
    path: "/product/unlink_ssp",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "updateSipItemPrice",
    path: "/product/update_sip_item_price",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getSizeChartList",
    path: "/product/get_size_chart_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getSizeChartDetail",
    path: "/product/get_size_chart_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getAllVehicleList",
    path: "/product/get_all_vehicle_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getVehicleListByCompatibilityDetail",
    path: "/product/get_vehicle_list_by_compatibility_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getAitemByPitemId",
    path: "/product/get_aitem_by_pitem_id",
    httpMethod: "GET",
    auth: true,
    commaParams: ["pitem_id_list"],
  },
  {
    group: "product",
    method: "getDirectShopRecommendedPrice",
    path: "/product/get_direct_shop_recommended_price",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "product",
    method: "getProductCertificationRule",
    path: "/product/get_product_certification_rule",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "searchUnpackagedModelList",
    path: "/product/search_unpackaged_model_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getMartItemMappingById",
    path: "/product/get_mart_item_mapping_by_id",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "getMartItemByOutletItemId",
    path: "/product/get_mart_item_by_outlet_item_id",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "product",
    method: "publishItemToOutletShop",
    path: "/product/publish_item_to_outlet_shop",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "public",
    method: "getShopsByPartner",
    path: "/public/get_shops_by_partner",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "public",
    method: "getMerchantsByPartner",
    path: "/public/get_merchants_by_partner",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "public",
    method: "getShopeeIpRange",
    path: "/public/get_shopee_ip_ranges",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "push",
    method: "setAppPushConfig",
    path: "/push/set_app_push_config",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "push",
    method: "getAppPushConfig",
    path: "/push/get_app_push_config",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "push",
    method: "getLostPushMessage",
    path: "/push/get_lost_push_message",
    httpMethod: "GET",
    auth: false,
  },
  {
    group: "push",
    method: "confirmConsumedLostPushMessage",
    path: "/push/confirm_consumed_lost_push_message",
    httpMethod: "POST",
    auth: false,
  },
  {
    group: "returns",
    method: "getReturnList",
    path: "/returns/get_return_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "getReturnDetail",
    path: "/returns/get_return_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "confirm",
    path: "/returns/confirm",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "dispute",
    path: "/returns/dispute",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "offer",
    path: "/returns/offer",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "acceptOffer",
    path: "/returns/accept_offer",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "getAvailableSolutions",
    path: "/returns/get_available_solutions",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "cancelDispute",
    path: "/returns/cancel_dispute",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "getReturnDisputeReason",
    path: "/returns/get_return_dispute_reason",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "convertImage",
    path: "/returns/convert_image",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "uploadProof",
    path: "/returns/upload_proof",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "queryProof",
    path: "/returns/query_proof",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "getShippingCarrier",
    path: "/returns/get_shipping_carrier",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "returns",
    method: "uploadShippingProof",
    path: "/returns/upload_shipping_proof",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "returns",
    method: "getReverseTrackingInfo",
    path: "/returns/get_reverse_tracking_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "sbs",
    method: "getBoundWhsInfo",
    path: "/sbs/get_bound_whs_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "sbs",
    method: "getCurrentInventory",
    path: "/sbs/get_current_inventory",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "sbs",
    method: "getExpiryReport",
    path: "/sbs/get_expiry_report",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "sbs",
    method: "getStockAging",
    path: "/sbs/get_stock_aging",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "sbs",
    method: "getStockMovement",
    path: "/sbs/get_stock_movement",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "getShopCategoryList",
    path: "/shop_category/get_shop_category_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "addShopCategory",
    path: "/shop_category/add_shop_category",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "updateShopCategory",
    path: "/shop_category/update_shop_category",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "deleteShopCategory",
    path: "/shop_category/delete_shop_category",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "addItemList",
    path: "/shop_category/add_item_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "deleteItemList",
    path: "/shop_category/delete_item_list",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopCategory",
    method: "getItemList",
    path: "/shop_category/get_item_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "getTimeSlotId",
    path: "/shop_flash_sale/get_time_slot_id",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "createShopFlashSale",
    path: "/shop_flash_sale/create_shop_flash_sale",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "getShopFlashSale",
    path: "/shop_flash_sale/get_shop_flash_sale",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "getShopFlashSaleList",
    path: "/shop_flash_sale/get_shop_flash_sale_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "updateShopFlashSale",
    path: "/shop_flash_sale/update_shop_flash_sale",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "deleteShopFlashSale",
    path: "/shop_flash_sale/delete_shop_flash_sale",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "addShopFlashSaleItems",
    path: "/shop_flash_sale/add_shop_flash_sale_items",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "getShopFlashSaleItems",
    path: "/shop_flash_sale/get_shop_flash_sale_items",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "updateShopFlashSaleItems",
    path: "/shop_flash_sale/update_shop_flash_sale_items",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "deleteShopFlashSaleItems",
    path: "/shop_flash_sale/delete_shop_flash_sale_items",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shopFlashSale",
    method: "getItemCriteria",
    path: "/shop_flash_sale/get_item_criteria",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getProfile",
    path: "/shop/get_profile",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getShopInfo",
    path: "/shop/get_shop_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "updateProfile",
    path: "/shop/update_profile",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "shop",
    method: "getWarehouseDetail",
    path: "/shop/get_warehouse_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getShopNotification",
    path: "/shop/get_shop_notification",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getAuthorisedResellerBrand",
    path: "/shop/get_authorised_reseller_brand",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getBRShopOnboardingInfo",
    path: "/shop/get_br_shop_onboarding_info",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "getShopHolidayMode",
    path: "/shop/get_shop_holiday_mode",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "shop",
    method: "setShopHolidayMode",
    path: "/shop/set_shop_holiday_mode",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "topPicks",
    method: "addTopPicks",
    path: "/top_picks/add_top_picks",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "topPicks",
    method: "deleteTopPicks",
    path: "/top_picks/delete_top_picks",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "topPicks",
    method: "getTopPicksList",
    path: "/top_picks/get_top_picks_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "topPicks",
    method: "updateTopPicks",
    path: "/top_picks/update_top_picks",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "video",
    method: "deleteVideo",
    path: "/video/delete_video",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "video",
    method: "editVideoInfo",
    path: "/video/edit_video_info",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "video",
    method: "getCoverList",
    path: "/video/get_cover_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getMetricTrend",
    path: "/video/get_metric_trend",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getOverviewPerformance",
    path: "/video/get_overview_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getProductPerformanceList",
    path: "/video/get_prodcut_performance_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getUserDemographics",
    path: "/video/get_user_demographics",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoDetail",
    path: "/video/get_video_detail",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoDetailAudienceDistribution",
    path: "/video/get_video_detail_audience_distribution",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoDetailMetricTrend",
    path: "/video/get_video_detail_metric_trend",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoDetailPerformance",
    path: "/video/get_video_detail_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoDetailProductPerformance",
    path: "/video/get_video_detail_product_performance",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoList",
    path: "/video/get_video_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "getVideoPerformanceList",
    path: "/video/get_video_performance_list",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "video",
    method: "postVideo",
    path: "/video/post_video",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "voucher",
    method: "addVoucher",
    path: "/voucher/add_voucher",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "voucher",
    method: "deleteVoucher",
    path: "/voucher/delete_voucher",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "voucher",
    method: "endVoucher",
    path: "/voucher/end_voucher",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "voucher",
    method: "updateVoucher",
    path: "/voucher/update_voucher",
    httpMethod: "POST",
    auth: true,
  },
  {
    group: "voucher",
    method: "getVoucher",
    path: "/voucher/get_voucher",
    httpMethod: "GET",
    auth: true,
  },
  {
    group: "voucher",
    method: "getVoucherList",
    path: "/voucher/get_voucher_list",
    httpMethod: "GET",
    auth: true,
  },
] as const satisfies readonly ShopeeSdkApiDefinition[];

export const SHOPEE_SDK_API_GROUP_NAMES = [
  "accountHealth",
  "addOnDeal",
  "ads",
  "ams",
  "auth",
  "bundleDeal",
  "discount",
  "fbs",
  "firstMile",
  "followPrize",
  "globalProduct",
  "livestream",
  "logistics",
  "media",
  "mediaSpace",
  "merchant",
  "order",
  "payment",
  "product",
  "public",
  "push",
  "returns",
  "sbs",
  "shop",
  "shopCategory",
  "shopFlashSale",
  "topPicks",
  "video",
  "voucher",
] as const;

export const SHOPEE_SDK_API_COUNT = SHOPEE_SDK_API_DEFINITIONS.length;

export function createShopeeSdkApiGroups(
  request: ShopeeSdkApiRequester,
): ShopeeSdkApiGroups {
  const groups: Record<string, ShopeeSdkApiGroup> = {};

  for (const groupName of SHOPEE_SDK_API_GROUP_NAMES) {
    groups[groupName] = {};
  }

  for (const definition of SHOPEE_SDK_API_DEFINITIONS) {
    groups[definition.group][definition.method] = (params?: any) =>
      request(definition, params);
  }

  return groups as unknown as ShopeeSdkApiGroups;
}
